### ISSUE TITLE
Automatically load kernel modules rather than requiring them to be listed

### ISSUE THREAD

**Issue by fhunleth** [mobileoverlord/bootloader#1]
It would be better if kernel modules didn't have to be listed for things that can be automatically detected. This mainly benefits wifi where we have more than one driver in the Nerves image and the adapter can always (to the best of my knowledge) be automatically detected. I think that we still want to support manual insertion even though I'd think that most people would compile the driver into the kernel.

The way to implement this is to traverse the `/sys` directory and read the `modalias` files. The contents of the `modalias` files can be passed on the commandline to `modprobe` and `modprobe` will figure out which driver to insert. Not all modalias's will insert and that's ok. There may be other details. I'm aware of the high level operation, but I've never dug into the details.

The second part of this is to monitor uevents for device insertion. When devices are inserted, the `modalias` file corresponding to that device should be inserted. This logic would appear to go in `nerves_runtime` now. It really seems like these packages should be unified somehow, but for now, just autoloading drivers on boot would address my issue with wifi module insertion.

**Comment by mobileoverlord** [comment]
This is more of an issue for `nerves_runtime` going to close this for now.
